#define LOAD_ASSETS0()  GD.safeloadSDIO(FileAsset);
#define MONEYBLACK_HANDLE 0
#define MONEYBLACK_WIDTH 60
#define MONEYBLACK_HEIGHT 40
#define MONEYBLACK_CELLS 1
#define MONEYRED_HANDLE 1
#define MONEYRED_WIDTH 60
#define MONEYRED_HEIGHT 40
#define MONEYRED_CELLS 1
#define ONEBLACK_HANDLE 2
#define ONEBLACK_WIDTH 60
#define ONEBLACK_HEIGHT 40
#define ONEBLACK_CELLS 1
#define ONERED_HANDLE 3
#define ONERED_WIDTH 60
#define ONERED_HEIGHT 40
#define ONERED_CELLS 1
#define SETTINGSBLACK_HANDLE 4
#define SETTINGSBLACK_WIDTH 60
#define SETTINGSBLACK_HEIGHT 40
#define SETTINGSBLACK_CELLS 1
#define SETTINGSRED_HANDLE 5
#define SETTINGSRED_WIDTH 60
#define SETTINGSRED_HEIGHT 40
#define SETTINGSRED_CELLS 1
#define THREEBLACK_HANDLE 6
#define THREEBLACK_WIDTH 60
#define THREEBLACK_HEIGHT 40
#define THREEBLACK_CELLS 1
#define THREERED_HANDLE 7
#define THREERED_WIDTH 60
#define THREERED_HEIGHT 40
#define THREERED_CELLS 1
#define TWOBLACK_HANDLE 8
#define TWOBLACK_WIDTH 60
#define TWOBLACK_HEIGHT 40
#define TWOBLACK_CELLS 1
#define TWORED_HANDLE 9
#define TWORED_WIDTH 60
#define TWORED_HEIGHT 40
#define TWORED_CELLS 1
#define ASSETS_END 48000UL
static const shape_t MONEYBLACK_SHAPE = {0, 60, 40, 0};
static const shape_t MONEYRED_SHAPE = {1, 60, 40, 0};
static const shape_t ONEBLACK_SHAPE = {2, 60, 40, 0};
static const shape_t ONERED_SHAPE = {3, 60, 40, 0};
static const shape_t SETTINGSBLACK_SHAPE = {4, 60, 40, 0};
static const shape_t SETTINGSRED_SHAPE = {5, 60, 40, 0};
static const shape_t THREEBLACK_SHAPE = {6, 60, 40, 0};
static const shape_t THREERED_SHAPE = {7, 60, 40, 0};
static const shape_t TWOBLACK_SHAPE = {8, 60, 40, 0};
static const shape_t TWORED_SHAPE = {9, 60, 40, 0};
